# typed: false
# frozen_string_literal: true

class Quarry < Formula
  include Language::Python::Virtualenv

  desc "Local semantic search engine — extract searchable knowledge from any document"
  homepage "https://github.com/punt-labs/quarry"
  url "https://files.pythonhosted.org/packages/source/p/punt-quarry/punt_quarry-1.3.9.tar.gz"
  sha256 "PLACEHOLDER"
  license "MIT"

  depends_on "python@3.13"

  # Resource stanzas for dependencies will be generated by:
  #   brew update-python-resources quarry
  # after the first release with correct PyPI metadata.

  def install
    virtualenv_install_with_resources
  end

  service do
    run [opt_bin/"quarry", "serve", "--port", "8420"]
    keep_alive true
    log_path var/"log/quarry.log"
    error_log_path var/"log/quarry.log"
  end

  test do
    assert_match "punt-quarry", shell_output("#{bin}/quarry version")
  end
end
